---
name: Wiki-Toolkit-Formatter-Mediawiki
version: 0.03
author:
  - 'Derek R. Price <derek@ximbiot.com>'
abstract: |-
  A Mediawiki-style formatter for
  Wiki::Toolkit.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Text::MediawikiFormat: 0.02
  URI::Escape: 0
build_requires:
  Test::More: 0
provides:
  Wiki::Toolkit::Formatter::Mediawiki:
    file: lib/Wiki/Toolkit/Formatter/Mediawiki.pm
    version: 0.03
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
